FROM eclipse-temurin:17-jdk-focal

#copy contents of backend_python to folder in container src
COPY ./authservice ./src
#set src as workig folder
WORKDIR src

ENV DB_URL="jdbc:postgresql://localhost:5432/habitus"
ENV DB_USERNAME="postgres"
ENV DB_PASSWORD="password"
ENV FRONTEND_URL="http://localhost:8001"

#prepare port
EXPOSE 8080
#run server
CMD ["./mvnw", "spring-boot:run"]