# Python Backend Dockerfile
FROM python:3.10-slim

# Copy application code
COPY . ./app

# Install dependencies
RUN pip install --no-cache-dir -r app/requirements.txt

# Run the application
EXPOSE 8000
# Host 0.0.0.0 is crucial for Docker
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
