FROM python:3.14-slim

#copy contents of backend_python to folder in container src
COPY . ./src
#set src as workig folder
WORKDIR src

#install requirements on image
RUN pip install -r requirements.txt

#prepare port
EXPOSE 8000
#run server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]