"""add_achievement_fields

Revision ID: 80876e34657d
Revises: 
Create Date: 2025-12-07 17:38:20.117266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80876e34657d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_password_reset_token_hash'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('idx_daily_checkins_user_habit_date'), table_name='daily_checkins')
    op.drop_table('daily_checkins')
    op.add_column('achievements', sa.Column('category', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('tier', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('icon_emoji', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('achievements', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('achievements', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('achievements', 'threshold_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('achievements', 'threshold_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('achievements', 'condition_type')
    op.drop_column('achievements', 'threshold')
    op.drop_column('achievements', 'created_at')
    op.drop_constraint(op.f('habit_tracker_user_habit_id_log_date_key'), 'habit_tracker', type_='unique')
    op.create_unique_constraint('uq_checkin_day', 'habit_tracker', ['user_habit_id', 'log_date'])
    op.drop_constraint(op.f('habit_tracker_user_habit_id_fkey'), 'habit_tracker', type_='foreignkey')
    op.create_foreign_key(None, 'habit_tracker', 'user_habits', ['user_habit_id'], ['id'])
    op.drop_column('habit_tracker', 'created_at')
    op.alter_column('habits', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('habits', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('habits', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('habits_user_id_fkey'), 'habits', type_='foreignkey')
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'])
    op.drop_column('habits', 'created_at')
    op.alter_column('user_achievements', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_achievements_user_id_achievement_id_key'), 'user_achievements', type_='unique')
    op.create_unique_constraint('uq_user_achievement_habit', 'user_achievements', ['user_id', 'achievement_id', 'habit_id'])
    op.drop_constraint(op.f('user_achievements_user_id_fkey'), 'user_achievements', type_='foreignkey')
    op.drop_constraint(op.f('user_achievements_achievement_id_fkey'), 'user_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievements', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_achievements', 'achievements', ['achievement_id'], ['id'])
    op.alter_column('user_habits', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_habits', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_habits', 'activated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_habits_user_id_habit_id_key'), 'user_habits', type_='unique')
    op.create_unique_constraint('uq_user_habit', 'user_habits', ['user_id', 'habit_id'])
    op.drop_constraint(op.f('user_habits_habit_id_fkey'), 'user_habits', type_='foreignkey')
    op.drop_constraint(op.f('user_habits_user_id_fkey'), 'user_habits', type_='foreignkey')
    op.create_foreign_key(None, 'user_habits', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_habits', 'habits', ['habit_id'], ['id'])
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_habits', type_='foreignkey')
    op.drop_constraint(None, 'user_habits', type_='foreignkey')
    op.create_foreign_key(op.f('user_habits_user_id_fkey'), 'user_habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_habits_habit_id_fkey'), 'user_habits', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_habit', 'user_habits', type_='unique')
    op.create_unique_constraint(op.f('user_habits_user_id_habit_id_key'), 'user_habits', ['user_id', 'habit_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_habits', 'activated_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_habits', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_habits', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('user_achievements_achievement_id_fkey'), 'user_achievements', 'achievements', ['achievement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_achievements_user_id_fkey'), 'user_achievements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_achievement_habit', 'user_achievements', type_='unique')
    op.create_unique_constraint(op.f('user_achievements_user_id_achievement_id_key'), 'user_achievements', ['user_id', 'achievement_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_achievements', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('habits', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.create_foreign_key(op.f('habits_user_id_fkey'), 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('habits', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('habits', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('habits', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('habit_tracker', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'habit_tracker', type_='foreignkey')
    op.create_foreign_key(op.f('habit_tracker_user_habit_id_fkey'), 'habit_tracker', 'user_habits', ['user_habit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_checkin_day', 'habit_tracker', type_='unique')
    op.create_unique_constraint(op.f('habit_tracker_user_habit_id_log_date_key'), 'habit_tracker', ['user_habit_id', 'log_date'], postgresql_nulls_not_distinct=False)
    op.add_column('achievements', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('condition_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('achievements', 'threshold_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('achievements', 'threshold_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('achievements', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('achievements', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('achievements', 'is_active')
    op.drop_column('achievements', 'icon_emoji')
    op.drop_column('achievements', 'tier')
    op.drop_column('achievements', 'category')
    op.create_table('daily_checkins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('habit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('daily_checkins_habit_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_checkins_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_checkins_pkey')),
    sa.UniqueConstraint('user_id', 'habit_id', 'date', name=op.f('daily_checkins_user_id_habit_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_daily_checkins_user_habit_date'), 'daily_checkins', ['user_id', 'habit_id', 'date'], unique=False)
    op.create_table('password_reset_token',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_token_pkey')),
    sa.UniqueConstraint('token_hash', name=op.f('password_reset_token_token_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_password_reset_token_hash'), 'password_reset_token', ['token_hash'], unique=False)
    # ### end Alembic commands ###
