-- Seed values for achievements users may get
INSERT INTO achievements (name, code, description, category, tier, icon_emoji, threshold_type, threshold_value) VALUES
('On a Roll', 'STREAK_3', 'Maintain a 3-day streak on a single habit.', 'streak', 'bronze', '🔥', 'per_habit_streak', 3),
('Work Week', 'STREAK_5', '5-day streak on a habit.', 'streak', 'bronze', '💼', 'per_habit_streak', 5),
('Weekly Warrior', 'STREAK_7', 'Maintain a 7-day streak on a single habit.', 'streak', 'silver', '🏅', 'per_habit_streak', 7),
('Double Digits', 'STREAK_10', '10-day streak on a habit.', 'streak', 'silver', '🔟', 'per_habit_streak', 10),
('Two-Week Blaze', 'STREAK_14', 'Maintain a 14-day streak on a single habit.', 'streak', 'gold', '⚡', 'per_habit_streak', 14),
('Habit Former', 'STREAK_21', 'Maintain a 21-day streak. Science says it takes 21 days!', 'streak', 'gold', '🧠', 'per_habit_streak', 21),
('Unbreakable', 'STREAK_30', 'Maintain a 30-day streak on a single habit.', 'streak', 'master', '🌟', 'per_habit_streak', 30),
('Quarantine Pro', 'STREAK_40', '40 days and 40 nights of discipline.', 'streak', 'master', '⛺', 'per_habit_streak', 40),
('Half Century', 'STREAK_50', 'Maintain a 50-day streak on a single habit.', 'streak', 'master', '🛡️', 'per_habit_streak', 50),
('Example Setter', 'STREAK_60', 'Two full months of consistency.', 'streak', 'master', '👩\u200d🏫', 'per_habit_streak', 60),
('Diamond Discipline', 'STREAK_75', '75 days of unbreakable will.', 'streak', 'master', '�', 'per_habit_streak', 75),
('Quarterly King', 'STREAK_90', '90 days - almost a full season!', 'streak', 'master', '🍂', 'per_habit_streak', 90),
('Centurion', 'STREAK_100', 'Reach a majestic 100-day streak.', 'streak', 'master', '👑', 'per_habit_streak', 100),
('Spartan', 'STREAK_200', '200 days of dedication.', 'streak', 'master', '⚔️', 'per_habit_streak', 200),
('Year of Greatness', 'STREAK_365', 'A full year streak. You are a legend.', 'streak', 'master', '📅', 'per_habit_streak', 365),
('First Steps', 'TOTAL_1', 'Complete your very first habit.', 'consistency', 'bronze', '�', 'total_completions', 1),
('High Five', 'TOTAL_5', 'Complete 5 habits.', 'consistency', 'bronze', '✋', 'total_completions', 5),
('Getting Started', 'TOTAL_10', 'Complete any habit 10 times.', 'consistency', 'bronze', '🎉', 'total_completions', 10),
('Picking Up Steam', 'TOTAL_25', 'Complete habits 25 times in total.', 'consistency', 'bronze', '�', 'total_completions', 25),
('Routine Builder', 'TOTAL_50', 'Complete habits 50 times in total.', 'consistency', 'silver', '�', 'total_completions', 50),
('Stacking Up', 'TOTAL_75', 'Complete habits 75 times in total.', 'consistency', 'silver', '�️', 'total_completions', 75),
('Century Club', 'TOTAL_100', 'Complete 100 habits total.', 'consistency', 'silver', '💯', 'total_completions', 100),
('Momentum Master', 'TOTAL_150', '150 completions. You''re rolling!', 'consistency', 'silver', '🌊', 'total_completions', 150),
('Habit Machine', 'TOTAL_250', 'Complete 250 habits total.', 'consistency', 'gold', '🤖', 'total_completions', 250),
('Consistency King', 'TOTAL_500', 'Complete 500 habits total.', 'consistency', 'gold', '🏰', 'total_completions', 500),
('Virtuoso', 'TOTAL_750', '750 completions. Pure dedication.', 'consistency', 'gold', '🎻', 'total_completions', 750),
('Legendary', 'TOTAL_1000', 'Complete 1,000 habits total.', 'consistency', 'master', '🦄', 'total_completions', 1000),
('Mythic', 'TOTAL_1500', '1,500 completions. Beyond legendary.', 'consistency', 'master', '🐉', 'total_completions', 1500),
('Ethereal', 'TOTAL_2500', '2,500 completions. Pure energy.', 'consistency', 'master', '🌌', 'total_completions', 2500),
('Universal', 'TOTAL_5000', '5,000 completions. You are the habit.', 'consistency', 'master', '🪐', 'total_completions', 5000);